---
# OS-Specific include of variables
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - netdata

# Install required packages
- import_tasks: packages.yml
  tags:
    - netdata
    - netdata_requirements

# Install netdata
- import_tasks: netdata.yml
  tags:
    - netdata
    - netdata_install