---
- name: Création du dossier git
  file:
    path: /git
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Checkout du repo git
  git:
    repo: https://github.com/firehol/netdata.git
    dest: /git/netdata
    depth: 1
  register: git_update

- name: Installation de netdata
  shell: "cd /git/netdata/ && ./netdata-installer.sh --dont-wait --libs-are-really-here"
  when: git_update.changed

- name: Déploiement de la configuration
  template:
    src: netdata.conf.j2
    dest: /etc/netdata/netdata.conf
  when: "netdata_config is defined"
