---
- name: Installation du repository epel
  yum:
    name: epel-release
    state: latest
  when: ansible_distribution == "CentOS"
  tags:
    - pkgs

- name: Installation des packages requis
  yum:
    name: "{{ item }}"
    state: latest
  with_items: "{{ netdata_pkgs_yum }}"
  when: ansible_distribution == "CentOS"
  tags:
    - pkgs

- name: Installation des packages requis
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ netdata_pkgs_apt }}"
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags:
    - pkgs
