---
- name: Add epel repository
  yum:
    name: "{{ netdata_yum_repos }}"
    state: latest
  when: ansible_distribution == "CentOS"

- name: Install packages
  package:
    name: "{{ netdata_pkgs }}"
    state: latest
  notify: restart netdata
...
